template/autotune_table_entry.cc: include iostream for cerr
This fixes build that does not define `NDEBUG` failing with:

```
(...)/aotriton/build/v2src/flash/autotune.bwd_preprocess/FONLY__^bf16@16,80,True___gfx1151.cc: In function ‘void aotriton::v2::flash::autotune::Autotune_bwd_preprocess__A0__F33(aotriton::v2::flash::BwdPreprocessParams&, int)’:
(...)/aotriton/build/v2src/flash/autotune.bwd_preprocess/FONLY__^bf16@16,80,True___gfx1151.cc:95:10: error: ‘cerr’ is not a member of ‘std’
   95 |     std::cerr << __FILE__ << " kernel_index = " << int(kernel_index) << std::endl;
      |          ^~~~
(...)/aotriton/build/v2src/flash/autotune.bwd_preprocess/FONLY__^bf16@16,80,True___gfx1151.cc:8:1: note: ‘std::cerr’ is defined in header ‘<iostream>’; this is probably fixable by adding ‘#include <iostream>’
    7 | #include <aotriton/cpp_tune.h>
  +++ |+#include <iostream>
    8 | #include <string_view>
```

The content of `template/autotune_table_entry.cc` will be duplicated into about 9000+ files
(depending on the number of arch to support) and any small overheads will
eventually be significant thus we condition inclusion of `<iostream>` on `NDEBUG` to
reduce static initialization work.